/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HexPubKeyModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HexPubKeyModelTests
    {
        // TODO uncomment below to declare an instance variable for HexPubKeyModel
        //private HexPubKeyModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HexPubKeyModel
            //instance = new HexPubKeyModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HexPubKeyModel
        /// </summary>
        [Test]
        public void HexPubKeyModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HexPubKeyModel
            //Assert.IsInstanceOfType<HexPubKeyModel> (instance, "variable 'instance' is a HexPubKeyModel");
        }


        /// <summary>
        /// Test the property 'PubKeyHex'
        /// </summary>
        [Test]
        public void PubKeyHexTest()
        {
            // TODO unit test for the property 'PubKeyHex'
        }

    }

}
