/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LocalCallContractRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LocalCallContractRequestTests
    {
        // TODO uncomment below to declare an instance variable for LocalCallContractRequest
        //private LocalCallContractRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LocalCallContractRequest
            //instance = new LocalCallContractRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LocalCallContractRequest
        /// </summary>
        [Test]
        public void LocalCallContractRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalCallContractRequest
            //Assert.IsInstanceOfType<LocalCallContractRequest> (instance, "variable 'instance' is a LocalCallContractRequest");
        }


        /// <summary>
        /// Test the property 'ContractAddress'
        /// </summary>
        [Test]
        public void ContractAddressTest()
        {
            // TODO unit test for the property 'ContractAddress'
        }
        /// <summary>
        /// Test the property 'MethodName'
        /// </summary>
        [Test]
        public void MethodNameTest()
        {
            // TODO unit test for the property 'MethodName'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'GasPrice'
        /// </summary>
        [Test]
        public void GasPriceTest()
        {
            // TODO unit test for the property 'GasPrice'
        }
        /// <summary>
        /// Test the property 'GasLimit'
        /// </summary>
        [Test]
        public void GasLimitTest()
        {
            // TODO unit test for the property 'GasLimit'
        }
        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

    }

}
