/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ScTxFeeEstimateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScTxFeeEstimateRequestTests
    {
        // TODO uncomment below to declare an instance variable for ScTxFeeEstimateRequest
        //private ScTxFeeEstimateRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScTxFeeEstimateRequest
            //instance = new ScTxFeeEstimateRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScTxFeeEstimateRequest
        /// </summary>
        [Test]
        public void ScTxFeeEstimateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScTxFeeEstimateRequest
            //Assert.IsInstanceOfType<ScTxFeeEstimateRequest> (instance, "variable 'instance' is a ScTxFeeEstimateRequest");
        }


        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }
        /// <summary>
        /// Test the property 'WalletName'
        /// </summary>
        [Test]
        public void WalletNameTest()
        {
            // TODO unit test for the property 'WalletName'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Test]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'Outpoints'
        /// </summary>
        [Test]
        public void OutpointsTest()
        {
            // TODO unit test for the property 'Outpoints'
        }
        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [Test]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }
        /// <summary>
        /// Test the property 'OpReturnData'
        /// </summary>
        [Test]
        public void OpReturnDataTest()
        {
            // TODO unit test for the property 'OpReturnData'
        }
        /// <summary>
        /// Test the property 'OpReturnAmount'
        /// </summary>
        [Test]
        public void OpReturnAmountTest()
        {
            // TODO unit test for the property 'OpReturnAmount'
        }
        /// <summary>
        /// Test the property 'FeeType'
        /// </summary>
        [Test]
        public void FeeTypeTest()
        {
            // TODO unit test for the property 'FeeType'
        }
        /// <summary>
        /// Test the property 'AllowUnconfirmed'
        /// </summary>
        [Test]
        public void AllowUnconfirmedTest()
        {
            // TODO unit test for the property 'AllowUnconfirmed'
        }
        /// <summary>
        /// Test the property 'ShuffleOutputs'
        /// </summary>
        [Test]
        public void ShuffleOutputsTest()
        {
            // TODO unit test for the property 'ShuffleOutputs'
        }
        /// <summary>
        /// Test the property 'ChangeAddress'
        /// </summary>
        [Test]
        public void ChangeAddressTest()
        {
            // TODO unit test for the property 'ChangeAddress'
        }

    }

}
