/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SendTransactionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SendTransactionRequestTests
    {
        // TODO uncomment below to declare an instance variable for SendTransactionRequest
        //private SendTransactionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SendTransactionRequest
            //instance = new SendTransactionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SendTransactionRequest
        /// </summary>
        [Test]
        public void SendTransactionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SendTransactionRequest
            //Assert.IsInstanceOfType<SendTransactionRequest> (instance, "variable 'instance' is a SendTransactionRequest");
        }


        /// <summary>
        /// Test the property 'Hex'
        /// </summary>
        [Test]
        public void HexTest()
        {
            // TODO unit test for the property 'Hex'
        }

    }

}
