/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SignMessageRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SignMessageRequestTests
    {
        // TODO uncomment below to declare an instance variable for SignMessageRequest
        //private SignMessageRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SignMessageRequest
            //instance = new SignMessageRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SignMessageRequest
        /// </summary>
        [Test]
        public void SignMessageRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignMessageRequest
            //Assert.IsInstanceOfType<SignMessageRequest> (instance, "variable 'instance' is a SignMessageRequest");
        }


        /// <summary>
        /// Test the property 'WalletName'
        /// </summary>
        [Test]
        public void WalletNameTest()
        {
            // TODO unit test for the property 'WalletName'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'ExternalAddress'
        /// </summary>
        [Test]
        public void ExternalAddressTest()
        {
            // TODO unit test for the property 'ExternalAddress'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
