/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SplitCoinsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SplitCoinsRequestTests
    {
        // TODO uncomment below to declare an instance variable for SplitCoinsRequest
        //private SplitCoinsRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SplitCoinsRequest
            //instance = new SplitCoinsRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SplitCoinsRequest
        /// </summary>
        [Test]
        public void SplitCoinsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SplitCoinsRequest
            //Assert.IsInstanceOfType<SplitCoinsRequest> (instance, "variable 'instance' is a SplitCoinsRequest");
        }


        /// <summary>
        /// Test the property 'WalletName'
        /// </summary>
        [Test]
        public void WalletNameTest()
        {
            // TODO unit test for the property 'WalletName'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Test]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'WalletPassword'
        /// </summary>
        [Test]
        public void WalletPasswordTest()
        {
            // TODO unit test for the property 'WalletPassword'
        }
        /// <summary>
        /// Test the property 'TotalAmountToSplit'
        /// </summary>
        [Test]
        public void TotalAmountToSplitTest()
        {
            // TODO unit test for the property 'TotalAmountToSplit'
        }
        /// <summary>
        /// Test the property 'UtxosCount'
        /// </summary>
        [Test]
        public void UtxosCountTest()
        {
            // TODO unit test for the property 'UtxosCount'
        }

    }

}
