/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// HexPubKeyModel
    /// </summary>
    [DataContract]
    public partial class HexPubKeyModel :  IEquatable<HexPubKeyModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HexPubKeyModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HexPubKeyModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HexPubKeyModel" /> class.
        /// </summary>
        /// <param name="pubKeyHex">pubKeyHex (required).</param>
        public HexPubKeyModel(string pubKeyHex = default(string))
        {
            // to ensure "pubKeyHex" is required (not null)
            if (pubKeyHex == null)
            {
                throw new InvalidDataException("pubKeyHex is a required property for HexPubKeyModel and cannot be null");
            }
            else
            {
                this.PubKeyHex = pubKeyHex;
            }
        }
        
        /// <summary>
        /// Gets or Sets PubKeyHex
        /// </summary>
        [DataMember(Name="pubKeyHex", EmitDefaultValue=false)]
        public string PubKeyHex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HexPubKeyModel {\n");
            sb.Append("  PubKeyHex: ").Append(PubKeyHex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HexPubKeyModel);
        }

        /// <summary>
        /// Returns true if HexPubKeyModel instances are equal
        /// </summary>
        /// <param name="input">Instance of HexPubKeyModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HexPubKeyModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PubKeyHex == input.PubKeyHex ||
                    (this.PubKeyHex != null &&
                    this.PubKeyHex.Equals(input.PubKeyHex))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PubKeyHex != null)
                    hashCode = hashCode * 59 + this.PubKeyHex.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
