/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SignMessageRequest
    /// </summary>
    [DataContract]
    public partial class SignMessageRequest :  IEquatable<SignMessageRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignMessageRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignMessageRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignMessageRequest" /> class.
        /// </summary>
        /// <param name="walletName">walletName (required).</param>
        /// <param name="password">password (required).</param>
        /// <param name="externalAddress">externalAddress (required).</param>
        /// <param name="message">message (required).</param>
        public SignMessageRequest(string walletName = default(string), string password = default(string), string externalAddress = default(string), string message = default(string))
        {
            // to ensure "walletName" is required (not null)
            if (walletName == null)
            {
                throw new InvalidDataException("walletName is a required property for SignMessageRequest and cannot be null");
            }
            else
            {
                this.WalletName = walletName;
            }
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new InvalidDataException("password is a required property for SignMessageRequest and cannot be null");
            }
            else
            {
                this.Password = password;
            }
            // to ensure "externalAddress" is required (not null)
            if (externalAddress == null)
            {
                throw new InvalidDataException("externalAddress is a required property for SignMessageRequest and cannot be null");
            }
            else
            {
                this.ExternalAddress = externalAddress;
            }
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new InvalidDataException("message is a required property for SignMessageRequest and cannot be null");
            }
            else
            {
                this.Message = message;
            }
        }
        
        /// <summary>
        /// Gets or Sets WalletName
        /// </summary>
        [DataMember(Name="walletName", EmitDefaultValue=false)]
        public string WalletName { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name="password", EmitDefaultValue=false)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets ExternalAddress
        /// </summary>
        [DataMember(Name="externalAddress", EmitDefaultValue=false)]
        public string ExternalAddress { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SignMessageRequest {\n");
            sb.Append("  WalletName: ").Append(WalletName).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  ExternalAddress: ").Append(ExternalAddress).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SignMessageRequest);
        }

        /// <summary>
        /// Returns true if SignMessageRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SignMessageRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SignMessageRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.WalletName == input.WalletName ||
                    (this.WalletName != null &&
                    this.WalletName.Equals(input.WalletName))
                ) && 
                (
                    this.Password == input.Password ||
                    (this.Password != null &&
                    this.Password.Equals(input.Password))
                ) && 
                (
                    this.ExternalAddress == input.ExternalAddress ||
                    (this.ExternalAddress != null &&
                    this.ExternalAddress.Equals(input.ExternalAddress))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WalletName != null)
                    hashCode = hashCode * 59 + this.WalletName.GetHashCode();
                if (this.Password != null)
                    hashCode = hashCode * 59 + this.Password.GetHashCode();
                if (this.ExternalAddress != null)
                    hashCode = hashCode * 59 + this.ExternalAddress.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
