/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// VerifyRequest
    /// </summary>
    [DataContract]
    public partial class VerifyRequest :  IEquatable<VerifyRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VerifyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyRequest" /> class.
        /// </summary>
        /// <param name="signature">signature (required).</param>
        /// <param name="externalAddress">externalAddress (required).</param>
        /// <param name="message">message (required).</param>
        public VerifyRequest(string signature = default(string), string externalAddress = default(string), string message = default(string))
        {
            // to ensure "signature" is required (not null)
            if (signature == null)
            {
                throw new InvalidDataException("signature is a required property for VerifyRequest and cannot be null");
            }
            else
            {
                this.Signature = signature;
            }
            // to ensure "externalAddress" is required (not null)
            if (externalAddress == null)
            {
                throw new InvalidDataException("externalAddress is a required property for VerifyRequest and cannot be null");
            }
            else
            {
                this.ExternalAddress = externalAddress;
            }
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new InvalidDataException("message is a required property for VerifyRequest and cannot be null");
            }
            else
            {
                this.Message = message;
            }
        }
        
        /// <summary>
        /// Gets or Sets Signature
        /// </summary>
        [DataMember(Name="signature", EmitDefaultValue=false)]
        public string Signature { get; set; }

        /// <summary>
        /// Gets or Sets ExternalAddress
        /// </summary>
        [DataMember(Name="externalAddress", EmitDefaultValue=false)]
        public string ExternalAddress { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VerifyRequest {\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("  ExternalAddress: ").Append(ExternalAddress).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VerifyRequest);
        }

        /// <summary>
        /// Returns true if VerifyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of VerifyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VerifyRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Signature == input.Signature ||
                    (this.Signature != null &&
                    this.Signature.Equals(input.Signature))
                ) && 
                (
                    this.ExternalAddress == input.ExternalAddress ||
                    (this.ExternalAddress != null &&
                    this.ExternalAddress.Equals(input.ExternalAddress))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Signature != null)
                    hashCode = hashCode * 59 + this.Signature.GetHashCode();
                if (this.ExternalAddress != null)
                    hashCode = hashCode * 59 + this.ExternalAddress.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
