/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AddressBookApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AddressBookApiTests
    {
        private AddressBookApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AddressBookApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddressBookApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AddressBookApi
            //Assert.IsInstanceOfType(typeof(AddressBookApi), instance, "instance is a AddressBookApi");
        }

        
        /// <summary>
        /// Test AddAddress
        /// </summary>
        [Test]
        public void AddAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AddressBookEntryRequest request = null;
            //instance.AddAddress(request);
            
        }
        
        /// <summary>
        /// Test GetAddressBook
        /// </summary>
        [Test]
        public void GetAddressBookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? skip = null;
            //int? take = null;
            //instance.GetAddressBook(skip, take);
            
        }
        
        /// <summary>
        /// Test RemoveAddress
        /// </summary>
        [Test]
        public void RemoveAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string label = null;
            //instance.RemoveAddress(label);
            
        }
        
    }

}
