/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BlockStoreApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BlockStoreApiTests
    {
        private BlockStoreApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BlockStoreApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlockStoreApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BlockStoreApi
            //Assert.IsInstanceOfType(typeof(BlockStoreApi), instance, "instance is a BlockStoreApi");
        }

        
        /// <summary>
        /// Test GetAddressIndexerTip
        /// </summary>
        [Test]
        public void GetAddressIndexerTipTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetAddressIndexerTip();
            
        }
        
        /// <summary>
        /// Test GetAddressesBalances
        /// </summary>
        [Test]
        public void GetAddressesBalancesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string addresses = null;
            //int? minConfirmations = null;
            //instance.GetAddressesBalances(addresses, minConfirmations);
            
        }
        
        /// <summary>
        /// Test GetBlock
        /// </summary>
        [Test]
        public void GetBlockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string hash = null;
            //bool? showTransactionDetails = null;
            //bool? outputJson = null;
            //instance.GetBlock(hash, showTransactionDetails, outputJson);
            
        }
        
        /// <summary>
        /// Test GetBlockCount
        /// </summary>
        [Test]
        public void GetBlockCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetBlockCount();
            
        }
        
        /// <summary>
        /// Test GetVerboseAddressesBalancesData
        /// </summary>
        [Test]
        public void GetVerboseAddressesBalancesDataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string addresses = null;
            //instance.GetVerboseAddressesBalancesData(addresses);
            
        }
        
    }

}
