/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DefaultVotingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DefaultVotingApiTests
    {
        private DefaultVotingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultVotingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultVotingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DefaultVotingApi
            //Assert.IsInstanceOfType(typeof(DefaultVotingApi), instance, "instance is a DefaultVotingApi");
        }

        
        /// <summary>
        /// Test GetFederationMembers
        /// </summary>
        [Test]
        public void GetFederationMembersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetFederationMembers();
            
        }
        
        /// <summary>
        /// Test GetFinishedPolls
        /// </summary>
        [Test]
        public void GetFinishedPollsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetFinishedPolls();
            
        }
        
        /// <summary>
        /// Test GetPendingPolls
        /// </summary>
        [Test]
        public void GetPendingPollsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetPendingPolls();
            
        }
        
        /// <summary>
        /// Test GetScheduledVotes
        /// </summary>
        [Test]
        public void GetScheduledVotesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetScheduledVotes();
            
        }
        
        /// <summary>
        /// Test GetWhitelistedHashes
        /// </summary>
        [Test]
        public void GetWhitelistedHashesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetWhitelistedHashes();
            
        }
        
        /// <summary>
        /// Test VoteRemoveHash
        /// </summary>
        [Test]
        public void VoteRemoveHashTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HashModel request = null;
            //instance.VoteRemoveHash(request);
            
        }
        
        /// <summary>
        /// Test VoteWhitelistHash
        /// </summary>
        [Test]
        public void VoteWhitelistHashTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HashModel request = null;
            //instance.VoteWhitelistHash(request);
            
        }
        
    }

}
