/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DiagnosticApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DiagnosticApiTests
    {
        private DiagnosticApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DiagnosticApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DiagnosticApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DiagnosticApi
            //Assert.IsInstanceOfType(typeof(DiagnosticApi), instance, "instance is a DiagnosticApi");
        }

        
        /// <summary>
        /// Test GetConnectedPeersInfo
        /// </summary>
        [Test]
        public void GetConnectedPeersInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetConnectedPeersInfo();
            
        }
        
        /// <summary>
        /// Test GetPeerStatistics
        /// </summary>
        [Test]
        public void GetPeerStatisticsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? connectedOnly = null;
            //var response = instance.GetPeerStatistics(connectedOnly);
            //Assert.IsInstanceOf<List<PeerStatisticsModel>> (response, "response is List<PeerStatisticsModel>");
        }
        
        /// <summary>
        /// Test GetStatus
        /// </summary>
        [Test]
        public void GetStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetStatus();
            
        }
        
        /// <summary>
        /// Test StartCollectingPeerStatistics
        /// </summary>
        [Test]
        public void StartCollectingPeerStatisticsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.StartCollectingPeerStatistics();
            
        }
        
        /// <summary>
        /// Test StopCollectingPeerStatistics
        /// </summary>
        [Test]
        public void StopCollectingPeerStatisticsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.StopCollectingPeerStatistics();
            
        }
        
    }

}
