/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DynamicContractApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DynamicContractApiTests
    {
        private DynamicContractApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DynamicContractApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DynamicContractApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DynamicContractApi
            //Assert.IsInstanceOfType(typeof(DynamicContractApi), instance, "instance is a DynamicContractApi");
        }

        
        /// <summary>
        /// Test CallMethod
        /// </summary>
        [Test]
        public void CallMethodTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string address = null;
            //string method = null;
            //instance.CallMethod(address, method);
            
        }
        
        /// <summary>
        /// Test LocalCallProperty
        /// </summary>
        [Test]
        public void LocalCallPropertyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string address = null;
            //string property = null;
            //instance.LocalCallProperty(address, property);
            
        }
        
    }

}
