/* 
 * Stratis Node API
 *
 * Access to the Stratis Node's core features.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FederationVotingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FederationVotingApiTests
    {
        private FederationVotingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FederationVotingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FederationVotingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FederationVotingApi
            //Assert.IsInstanceOfType(typeof(FederationVotingApi), instance, "instance is a FederationVotingApi");
        }

        
        /// <summary>
        /// Test VoteAddFedMember
        /// </summary>
        [Test]
        public void VoteAddFedMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HexPubKeyModel request = null;
            //instance.VoteAddFedMember(request);
            
        }
        
        /// <summary>
        /// Test VoteKickFedMember
        /// </summary>
        [Test]
        public void VoteKickFedMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HexPubKeyModel request = null;
            //instance.VoteKickFedMember(request);
            
        }
        
    }

}
